name: Autograding Tests
'on':
- push
- repository_dispatch
permissions:
  checks: write
  actions: read
  contents: read
jobs:
  run-autograding-tests:
    runs-on: ubuntu-latest
    if: github.actor != 'github-classroom[bot]'
    steps:
    - name: Checkout code
      uses: actions/checkout@v4
    - name: Matrix output test
      id: matrix-output-test
      uses: classroom-resources/autograding-command-grader@v1
      with:
        test-name: Matrix output test
        setup-command: ''
        command: make test
        timeout: 10
        max-score: 2
    - name: No args test
      id: no-args-test
      uses: classroom-resources/autograding-command-grader@v1
      with:
        test-name: No args test
        setup-command: chmod +x checkargs.sh
        command: ./checkargs "./assignment" "Incorrect usage. You provided 0 arguments.
          The correct number of arguments is 2"
        timeout: 10
        max-score: 1
    - name: Autograding Reporter
      uses: classroom-resources/autograding-grading-reporter@v1
      env:
        MATRIX-OUTPUT-TEST_RESULTS: "${{steps.matrix-output-test.outputs.result}}"
        NO-ARGS-TEST_RESULTS: "${{steps.no-args-test.outputs.result}}"
      with:
        runners: matrix-output-test,no-args-test
